# Generated by Django 2.2.12 on 2024-12-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20241206_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ville',
            field=models.TextField(default='Abobo'),
        ),
    ]
