# Generated by Django 2.2.12 on 2024-12-08 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_cours_description'),
        ('instructor', '0005_instructor_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='cours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_cours', to='school.Cours'),
        ),
    ]
