# Generated by Django 2.2.12 on 2024-12-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_instructor_cours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='cours',
        ),
    ]
